# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "box" do |box|
    box.vm.hostname = "box"
    box.vm.network :private_network, ip: "192.168.69.2"
  end

  config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
  end
end
