apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.16.1
  nodeSets:
    - name: default
      count: 2
      config:
        node.store.allow_mmap: false
