install:
	flux bootstrap git --url=git@github.com/bahybintang/learn-sre.git --branch=master --path=fluxcd/dev
installs:
	flux bootstrap github \
		--owner=bahybintang \
		--repository=learn-sre \
		--branch=master \
		--path=./fluxcd/dev \
		--personal